name: Create Image
on:
  workflow_dispatch:
jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Packer
        uses: hashicorp/setup-packer@main

      - name: Packer Init
        run: packer init .
        working-directory: provision 

      - name: Save Ansible Vault Secret
        shell: bash
        run: |
          echo "${ANSIBLE_VAULT_SECRET}" > vaultpassword
        working-directory: provision 
        env:
          ANSIBLE_VAULT_SECRET: ${{ secrets.ANSIBLE_VAULT_SECRET }}

      - name: Packer Build
        run: packer build core.pkr.hcl 
        working-directory: provision 
        env:
          PKR_VAR_digitalocean_token: ${{ secrets.DO_TOKEN }}

