name: Provision VM
on:
  workflow_dispatch:
jobs:
  infrastructure:
    outputs:
      droplet_ip: ${{ steps.dropletIP.outputs.IP_ADDR }}
    runs-on: ubuntu-latest
    env:
      TF_VAR_digitalocean_token: ${{ secrets.DO_TOKEN }}
      TF_VAR_ssh_private_key_path: ./terraform/ssh_key
      AWS_ACCESS_KEY_ID: ${{ secrets.B2_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.B2_APPLICATION_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      - bash: |
          echo "${{ secrets.PRIVATE_KEY }}" > ./terraform/ssh_key
          chmod 600 ./terraform/ssh_key

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: ./terraform

      - name: Terraform Init
        run: terraform init 
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Get Droplet IP
        id: dropletIP
        run: |
          echo IP_ADDR=`terraform output -json | jq '.droplet_ip.value' -r` >> $GITHUB_OUTPUT
        working-directory: ./terraform
  provision:
    runs-on: ubuntu-latest
    needs: infrastructure
    steps:
      - uses: actions/checkout@v3
      - bash: |
          echo "${{ secrets.PRIVATE_KEY }}" > ./terraform/ssh_key
          chmod 600 ./terraform/ssh_key
      

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v7
        with:
          playbook: install-hugging-face.yaml
          directory: ./provision
          key: ${{secrets.PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [all]
            ${{ needs.infrastructure.outputs.droplet_ip }}
          vault_password: ${{secrets.ANSIBLE_VAULT_SECRET }}
