name: Provision VM
on:
  workflow_dispatch:
jobs:
  infrastructure:
    outputs:
      droplet_ip: ${{ steps.dropletIP.outputs.IP_ADDR }}
    runs-on: ubuntu-latest
    env:
      TF_VAR_digitalocean_token: ${{ secrets.DO_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.B2_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.B2_APPLICATION_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: ./terraform

      - name: Terraform Init
        run: terraform init 
        working-directory: ./terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Get Droplet IP
        id: dropletIP
        run: |
          echo IP_ADDR=`terraform output -json | jq '.droplet_ip.value' -r` >> $GITHUB_OUTPUT
        working-directory: ./terraform
  provision:
    runs-on: ubuntu-latest
    needs: infrastructure



    env:
      TF_VAR_digitalocean_token: ${{ secrets.DO_TOKEN }}
      AWS_ACCESS_KEY_ID: ${{ secrets.B2_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.B2_APPLICATION_KEY }}
    steps:
      - uses: actions/checkout@v3

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@<REF>
        with:
          playbook: install-hugging-face.yaml
          directory: ./provision
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [all]
            example.com

            [group1]
            example.com
          # Optional, SSH known hosts file content
          known_hosts: |
            example.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          vault_password: ${{secrets.ANSIBLE_VAULT_SECRET }}
